### ISSUE TITLE
Prevent HTTP forwarders from hitting admin endpoints

### ISSUE THREAD

**Issue by nullmonk** [RITRedteam/TheLibrary#1]
Perhaps add all admin features under a `/admin/` path and prevent that path from being forwarded in the NGINX forwarder.

**Comment by Cictrone** [comment]
Did we want that or the inverse where links are in a /link/ path?

**Comment by nullmonk** [comment]
That could work, Maybe like `/l/` so it can be shorter

**Comment by Cictrone** [comment]
see commit  8e961dd
